### ISSUE TITLE
把sts-sdk迁移到github上来

### ISSUE THREAD

**Issue by edwardaa** [aliyun/sts-demo-simple-android-app#3]
在`aliyun_OSS_Android_SDK_20150701.zip`里有`sts-javaclientsdk` `sts-phpclientsdk` `sts-pythonclientsdk` 三个`SDK`，希望您能把它们都迁移到`GitHub`上来，这样在项目中可以直接引用，非常方便。

**Comment by oldratlee** [comment]
应该如此。

这事在进行中，我问一下相关的同学，尽快做好 :smile:

**Comment by oldratlee** [comment]
`STS`多种语言的`SDK`的代码已经放出来了， https://github.com/aliyun 下 `aliyun-openapi`开头的工程就是。
