### ISSUE TITLE
aliyun-php-sdk-core的DefaultProfile里变量书写错误

### ISSUE THREAD

**Issue by edwardaa** [aliyun/sts-demo-simple-android-app#4]
嗨，李鼎，我猜测向您提这个问题比较合适，在`DefaultProfile`类里由于书写错误导致`Undefined variable productDomains`类型的错误：
![undefined_variable](https://cloud.githubusercontent.com/assets/8274162/8817357/f1df170a-3064-11e5-9c51-307c99eaac33.png)

这个SDK是在`aliyun_OSS_Android_SDK_20150701.zip/oss_android_sdk/sts-sdk/sts-phpclientsdk`找到的。

**Comment by oldratlee** [comment]
你说是 `STS`的`PHP SDK`的问题？ `oss_android_sdk`的问题？

> 这个SDK是在aliyun_OSS_Android_SDK_20150701.zip/oss_android_sdk/sts-sdk/sts-phpclientsdk找到的。

上面的信息我找不到 你的说的代码 在哪儿（下载的链接）。

- `PHP`我不熟悉，你可以直接发一下 `STS`的工单。
- `STS`的`SDK`的代码已经放出来了 https://github.com/aliyun 下 `aliyun-openapi`开头的工程就是。

**Comment by edwardaa** [comment]
OK, thanks!

close it
